### ISSUE TITLE
Some radio buttons and checkboxes are broken

### ISSUE THREAD

**Issue by npearson72** [Jannomag/Yaru-Colors#4] opened 2019-10-11 14:13 UTC
![Screenshot from 2019-10-11 07-08-59](https://user-images.githubusercontent.com/1323414/66658518-7fcaf380-ebf6-11e9-913e-528e3d59f666.png)

**Comment by rosaastrum** [comment] 2019-10-12 11:56
Can confirm the same thing, only seems to happen on the dark variants for me.

**Comment by jecsham** [comment] 2019-10-13 23:23
I can confirm as well. Only happening in dark themes.

**Comment by Jannomag** [comment] 2019-11-01 16:24
Sorry for the late response - I had no time to fix it. 
It's fixed now...I updated the installer script - please redownload and rerun the installer script (no need for uninstall, it just overwrites everything).

This issue was caused by missing symbolic links to the assets directories in gtk-3.0 and gtk-3.20 directories of each theme. The updated installer will create them now.

**Closed** 2019-11-01 16:25 UTC
